// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: txpoker/stats_cache_group.proto

package txpokergrpc

import (
	_ "card-game-server-prototype/pkg/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	HighestGameWinAmount int32             `protobuf:"varint,2,opt,name=highest_game_win_amount,json=highestGameWinAmount,proto3" json:"highest_game_win_amount,omitempty"`
	EventSums            []*Stats_EventSum `protobuf:"bytes,3,rep,name=event_sums,json=eventSums,proto3" json:"event_sums,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpoker_stats_cache_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_txpoker_stats_cache_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_txpoker_stats_cache_group_proto_rawDescGZIP(), []int{0}
}

func (x *Stats) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Stats) GetHighestGameWinAmount() int32 {
	if x != nil {
		return x.HighestGameWinAmount
	}
	return 0
}

func (x *Stats) GetEventSums() []*Stats_EventSum {
	if x != nil {
		return x.EventSums
	}
	return nil
}

type StatsCacheGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats map[string]*Stats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StatsCacheGroup) Reset() {
	*x = StatsCacheGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpoker_stats_cache_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsCacheGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsCacheGroup) ProtoMessage() {}

func (x *StatsCacheGroup) ProtoReflect() protoreflect.Message {
	mi := &file_txpoker_stats_cache_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsCacheGroup.ProtoReflect.Descriptor instead.
func (*StatsCacheGroup) Descriptor() ([]byte, []int) {
	return file_txpoker_stats_cache_group_proto_rawDescGZIP(), []int{1}
}

func (x *StatsCacheGroup) GetStats() map[string]*Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Stats_EventSum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   StatsEventType `protobuf:"varint,1,opt,name=type,proto3,enum=txpoker.statsevent.StatsEventType" json:"type,omitempty"`
	Amount int32          `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Stats_EventSum) Reset() {
	*x = Stats_EventSum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpoker_stats_cache_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats_EventSum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats_EventSum) ProtoMessage() {}

func (x *Stats_EventSum) ProtoReflect() protoreflect.Message {
	mi := &file_txpoker_stats_cache_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats_EventSum.ProtoReflect.Descriptor instead.
func (*Stats_EventSum) Descriptor() ([]byte, []int) {
	return file_txpoker_stats_cache_group_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Stats_EventSum) GetType() StatsEventType {
	if x != nil {
		return x.Type
	}
	return StatsEventType_UNDEFINED
}

func (x *Stats_EventSum) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_txpoker_stats_cache_group_proto protoreflect.FileDescriptor

var file_txpoker_stats_cache_group_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x13, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe4, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x17, 0x68,
	0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x68, 0x69,
	0x67, 0x68, 0x65, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x75, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x6d, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x6d, 0x73, 0x1a, 0x5a, 0x0a, 0x08, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x6d, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x78, 0x70, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x48, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x6b, 0x5a, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x78, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x67, 0x72,
	0x70, 0x63, 0xaa, 0x02, 0x1d, 0x4a, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x70,
	0x6c, 0x61, 0x79, 0x2e, 0x54, 0x78, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0xca, 0xb2, 0x04, 0x16, 0x4a, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x70, 0x6c, 0x61, 0x79, 0x2e, 0x54, 0x78, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_txpoker_stats_cache_group_proto_rawDescOnce sync.Once
	file_txpoker_stats_cache_group_proto_rawDescData = file_txpoker_stats_cache_group_proto_rawDesc
)

func file_txpoker_stats_cache_group_proto_rawDescGZIP() []byte {
	file_txpoker_stats_cache_group_proto_rawDescOnce.Do(func() {
		file_txpoker_stats_cache_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_txpoker_stats_cache_group_proto_rawDescData)
	})
	return file_txpoker_stats_cache_group_proto_rawDescData
}

var file_txpoker_stats_cache_group_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_txpoker_stats_cache_group_proto_goTypes = []interface{}{
	(*Stats)(nil),           // 0: txpoker.Stats
	(*StatsCacheGroup)(nil), // 1: txpoker.StatsCacheGroup
	(*Stats_EventSum)(nil),  // 2: txpoker.Stats.EventSum
	nil,                     // 3: txpoker.StatsCacheGroup.StatsEntry
	(StatsEventType)(0),     // 4: txpoker.statsevent.StatsEventType
}
var file_txpoker_stats_cache_group_proto_depIdxs = []int32{
	2, // 0: txpoker.Stats.event_sums:type_name -> txpoker.Stats.EventSum
	3, // 1: txpoker.StatsCacheGroup.stats:type_name -> txpoker.StatsCacheGroup.StatsEntry
	4, // 2: txpoker.Stats.EventSum.type:type_name -> txpoker.statsevent.StatsEventType
	0, // 3: txpoker.StatsCacheGroup.StatsEntry.value:type_name -> txpoker.Stats
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_txpoker_stats_cache_group_proto_init() }
func file_txpoker_stats_cache_group_proto_init() {
	if File_txpoker_stats_cache_group_proto != nil {
		return
	}
	file_txpoker_stats_event_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_txpoker_stats_cache_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpoker_stats_cache_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsCacheGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpoker_stats_cache_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats_EventSum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_txpoker_stats_cache_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txpoker_stats_cache_group_proto_goTypes,
		DependencyIndexes: file_txpoker_stats_cache_group_proto_depIdxs,
		MessageInfos:      file_txpoker_stats_cache_group_proto_msgTypes,
	}.Build()
	File_txpoker_stats_cache_group_proto = out.File
	file_txpoker_stats_cache_group_proto_rawDesc = nil
	file_txpoker_stats_cache_group_proto_goTypes = nil
	file_txpoker_stats_cache_group_proto_depIdxs = nil
}
