// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package commontest

import (
	"card-game-server-prototype/pkg/common"
	"card-game-server-prototype/pkg/common/api"
	"card-game-server-prototype/pkg/common/model"
	"card-game-server-prototype/pkg/common/service"
	"card-game-server-prototype/pkg/config"
	"card-game-server-prototype/pkg/core"
	"card-game-server-prototype/pkg/util"
	"github.com/google/wire"
)

// Injectors from build_registry.go:

func BuildRegistry() (*Registry, error) {
	logConfig := _wireLogConfigValue
	loggerFactory := util.ProvideLoggerFactory(logConfig)
	client := util.ProvideHttpClient(loggerFactory)
	apiConfig := _wireAPIConfigValue
	baseRoomAPI := api.ProvideBaseRoomAPI(client, apiConfig)
	baseUserAPI := api.ProvideBaseUserAPI(client, apiConfig)
	commontestApiRegistry := ProvideAPIRegistry(baseRoomAPI, baseUserAPI)
	userGroup := model.ProvideUserGroup(loggerFactory)
	msgBus := core.ProvideMsgBus(loggerFactory)
	roomInfo := model.ProvideRoomInfo()
	baseUserService := service.ProvideBaseUserService(userGroup, msgBus, roomInfo, baseUserAPI, baseRoomAPI, loggerFactory)
	commontestServiceRegistry := ProvideServiceRegistry(baseUserService)
	registry := ProvideRegistry(commontestApiRegistry, commontestServiceRegistry)
	return registry, nil
}

var (
	_wireLogConfigValue = config.LogCFG
	_wireAPIConfigValue = config.APICFG
)

// build_registry.go:

var providerSet = wire.NewSet(config.ProviderSet, core.ProviderSet, common.ProviderSet, util.ProviderSet)
